[package]
name = "project"
version = "0.1.0"
authors = ["martin"]

[dependencies]
coco = "0.3.3"
itertools = "0.7.4"
rand="0.3"
ansi-escapes = "0.1.0"
ncurses = "5.87.0"

[lib]
name = "reactivers"
path = "src/lib.rs"

[[bin]]
name = "trafficsim"
path = "src/main.rs"